branches:
  except:
  - /.*(.tmp)$/

language: rust

matrix:
  include:
  - os: osx
    rust: 1.22.0
  - os: osx
    rust: nightly
  - rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
  - os: linux
    rust: nightly
    script:
    - cargo test --features "const_fn"

notifications:
  email:
    on_success: never

os: linux

rust:
- 1.22.0
- stable
- beta
- nightly

sudo: false
